version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: 'bd_mysql_back'
    ports:
      - "3306:3306"  # Проброс порта 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kataschema

  app:
    build: ./
    container_name: 'java-app_back'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/kataschema
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

